name: Test PR
run-name: Test PR ${{ github.event.number }} «${{ github.event.pull_request.title }}» (${{ github.actor}})
on:
  pull_request:
    types:
      - opened
      - synchronize
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:

  Build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build binary
        run: dotnet build -c Release -o bin --nologo src/Regale/Regale.csproj
      - name: Upload binary artefact
        uses: actions/upload-artifact@v3
        with:
          name: build-binary
          path: bin

  TestOnInstance:
    name: Test instance ${{ matrix.num }}
    runs-on: ubuntu-latest
    needs:
      - Build
    strategy:
      matrix:
        num: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Download Binary
        uses: actions/download-artifact@v3
        continue-on-error: false
        with:
          name: build-binary
          path: bin
      - name: Make binary executable
        run: chmod +x bin/Regale
      - run: ls -la
      - run: ls -la vendor
      - run: ls -la vendor/aufgabe
      - run: ls -la vendor/aufgabe/solution-checker
      - run: ls -la vendor/aufgabe/solution-checker/input
      - name: Run test
        run: bin/Regale "vendor/aufgabe/solution-checker/input/instance${{ matrix.num }}.json" -

  DotnetTest:
    name: Execute Dotnet test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Execute dotnet test
        run: dotnet test
        working-directory: src
      - name: Upload test artefacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            src/Regale.Test/TestResults
