name: Test PR
run-name: Test PR ${{ github.event.number }} «${{ github.event.pull_request.title }}» (${{ github.actor}})
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_call:
  push:
    branches:
      - main
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:

  Build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build binary
        run: dotnet build -c Release -o bin --nologo src/Regale/Regale.csproj
      - name: Upload binary artefact
        uses: actions/upload-artifact@v3
        with:
          name: build-binary
          path: bin

  TestOnInstance:
    name: Test instance ${{ matrix.num }}
    runs-on: ubuntu-latest
    needs:
      - Build
    strategy:
      matrix:
        num: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Download Binary
        uses: actions/download-artifact@v3
        continue-on-error: false
        with:
          name: build-binary
          path: bin
      - name: Make binary executable
        run: chmod +x bin/Regale
      - name: Copy input file to input directory
        run: |
          mkdir -p input
          cp "vendor/aufgabe/solution-checker/input/instance${{ matrix.num }}.json" input/
      - name: Run test
        run: bin/Regale "input/instance${{ matrix.num }}.json" "output/instance${{ matrix.num }}.json"
      - name: Verify using provided checker
        run: |
          mkdir -p result
          python vendor/aufgabe/solution-checker/solution_checker.py \
            | tee result/res${{ matrix.num }}.txt \
            | tee -a $GITHUB_STEP_SUMMARY
          grep -q "Valid" result/res${{ matrix.num }}.txt
          exit $?
      - name: Upload output artefact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-instance-output
          path: output
      - name: Upload result artefact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-instance-result
          path: result

  DockerTest:
    name: Run Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create docker container
        run: docker build -t regale .
      - name: Run docker container
        run: |
          docker run \
            -v "$(pwd)/vendor/aufgabe/solution-checker/input:/input" \
            -v "$(pwd)/output:/output" \
            regale

  DotnetTest:
    name: Execute Dotnet test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Execute dotnet test
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: src
      - name: Upload test artefacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            src/Regale.Test/TestResults

  GenerateReports:
    name: Generate Coverage Reports
    needs:
      - DotnetTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install Report Generator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.21
      - name: Download Reports
        uses: actions/download-artifact@v3
        continue-on-error: false
        with:
          name: test-reports
      - name: Generate Reports
        run: |
          reportgenerator \
            "-reports:**/coverage.cobertura.xml" \
            -targetdir:report \
            "-reporttypes:Html;Badges" \
            "-title:Relaxdays Hackathon 4 - Bewegliche Regale" \
            -tag:$(git rev-parse --short HEAD)
      - name: Upload Report artefacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            report
